version: '3.8'

services:
  telethon-bot:
    build: .
    container_name: telethon-channel-parser
    restart: unless-stopped
    ports:
      - "8010:8010"
    volumes:
      # Монтируем сессии Telegram для сохранения аутентификации
      - ./sessions:/app/sessions
      # Монтируем базу данных для сохранения данных
      - ./data:/app/data
      # Монтируем логи
      - ./logs:/app/logs
      # Монтируем .env файл
      - ./.env:/app/.env
    environment:
      # Переменные окружения (будут переопределены из .env файла)
      - HOST=0.0.0.0
      - PORT=8010
      - PARSER_INTERVAL_MINUTES=30
      - DATABASE_URL=sqlite:///./data/telethon_bot.db
    networks:
      - telethon-network

  # Опционально: PostgreSQL для продакшена
  # postgres:
  #   image: postgres:15
  #   container_name: telethon-postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: telethon_bot
  #     POSTGRES_USER: telethon_user
  #     POSTGRES_PASSWORD: telethon_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - telethon-network

networks:
  telethon-network:
    driver: bridge

# volumes:
#   postgres_data: 