global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "n8n"
    static_configs:
      - targets: ["n8n:5678"]

  - job_name: "n8n-worker"
    static_configs:
      - targets: ["n8n-worker:5679"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Telegram Bot metrics
  - job_name: "telegram-bot"
    static_configs:
      - targets: ["telethon:8010"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # RAG Service metrics  
  - job_name: "rag-service"
    static_configs:
      - targets: ["rag-service:8020"]
    metrics_path: "/metrics"
    scrape_interval: 30s
